// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqfEAlv9JkASpf1m7vpKQil6wWmsR-X4I',
    appId: '1:842676163233:web:dc6c2b0cbed3fa7c0f96e0',
    messagingSenderId: '842676163233',
    projectId: 'secrethitler-privado',
    authDomain: 'secrethitler-privado.firebaseapp.com',
    storageBucket: 'secrethitler-privado.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDIv7MlqnzuV4vfYFZvbwIqEfvR3nvOrE',
    appId: '1:842676163233:android:9efaf823349375110f96e0',
    messagingSenderId: '842676163233',
    projectId: 'secrethitler-privado',
    storageBucket: 'secrethitler-privado.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqeI65jzl6bgFw2TRkOv9vSEdKm_jTo4c',
    appId: '1:842676163233:ios:f510b3ac50e5161b0f96e0',
    messagingSenderId: '842676163233',
    projectId: 'secrethitler-privado',
    storageBucket: 'secrethitler-privado.firebasestorage.app',
    iosBundleId: 'com.example.secrethitlerGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqfEAlv9JkASpf1m7vpKQil6wWmsR-X4I',
    appId: '1:842676163233:web:0f2f2235c93d92d90f96e0',
    messagingSenderId: '842676163233',
    projectId: 'secrethitler-privado',
    authDomain: 'secrethitler-privado.firebaseapp.com',
    storageBucket: 'secrethitler-privado.firebasestorage.app',
  );
}
